CREATE TABLE [dbo].[Category]
(
    [SG_KEY] INT NOT NULL PRIMARY KEY CLUSTERED IDENTITY,
    [Id] UNIQUEIDENTIFIER NOT NULL,
    [Name] NVARCHAR(MAX) NOT NULL, 
    [ProjectCount] INT NOT NULL
)

GO
CREATE UNIQUE INDEX [KeyIndex] ON [dbo].[Category] ([Id])